{
 "title": "weir全局监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(weirproxy_queryctx_query_total{job=~\"test\"},instance)"
   },
   { "name": "quantile", "label": "分位", "query": "99,95,90,80,70,50" }
  ]
 },
 "panels": [
  {
   "title": "正常查询QPS (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weirproxy_queryctx_query_total{job=~\"test\",result=\"ok\"}[10s])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "异常查询QPS (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weirproxy_queryctx_query_total{job=~\"test\",result=\"err\"}[10s])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "查询耗时 (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile/100, sum(rate(weirproxy_queryctx_handle_query_duration_seconds_bucket{job=~\"test\"}[10s])) by (namespace,le))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "正常查询QPS (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weirproxy_queryctx_query_total{job=~\"test\",result=\"ok\"}[10s])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "异常查询QPS (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weirproxy_queryctx_query_total{job=~\"test\",result=\"err\"}[10s])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "查询耗时 (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile/100, sum(rate(weirproxy_queryctx_handle_query_duration_seconds_bucket{job=~\"test\"}[10s])) by (instance,le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "客户端连接数 (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_queryctx_queryctx{job=~\"test\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "客户端事务/Prepare连接数 (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_queryctx_attached_connections{job=~\"test\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "后端连接池使用数 (路由)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_backend_b_conn_in_use{job=~\"test\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "客户端连接数 (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_queryctx_queryctx{job=~\"test\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "客户端事务/Prepare连接数 (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_queryctx_attached_connections{job=~\"test\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "后端连接池使用数 (实例)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weirproxy_backend_b_conn_in_use{job=~\"test\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "goroutine",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{service=\"\",job=\"test\"}) by (service,instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{service=\"\",job=\"test\"}[10s]) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{service=\"\",job=\"test\"}[10s]) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}