version: "v1"
namespace: "test_namespace"
frontend:
  allowed_dbs:
    - "test_weir_db"
  slow_sql_time: 50
  denied_sqls:
  denied_ips:
  idle_timeout: 3600
  users:
    - username: "hello"
      password: "world"
    - username: "hello1"
      password: "world1"
backend:
  instances:
    - "127.0.0.1:4000"
  username: "root"
  password: ""
  selector_type: "random"
  pool_size: 10
  idle_timeout: 60
breaker:
  scope: "sql"
  strategies:
    - min_qps: 3
      failure_ratethreshold: 0
      failure_num: 5
      sql_timeoutMs: 2000
      open_status_durationMs: 5000
      size: 10
      cellIntervalMs: 1000