// Code generated by mockery v2.3.0. DO NOT EDIT.

package driver

import mock "github.com/stretchr/testify/mock"

// MockNamespaceManager is an autogenerated mock type for the NamespaceManager type
type MockNamespaceManager struct {
	mock.Mock
}

// Auth provides a mock function with given fields: username, pwd, salt
func (_m *MockNamespaceManager) Auth(username string, pwd []byte, salt []byte) (Namespace, bool) {
	ret := _m.Called(username, pwd, salt)

	var r0 Namespace
	if rf, ok := ret.Get(0).(func(string, []byte, []byte) Namespace); ok {
		r0 = rf(username, pwd, salt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Namespace)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string, []byte, []byte) bool); ok {
		r1 = rf(username, pwd, salt)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
