// Code generated by mockery v2.3.0. DO NOT EDIT.

package driver

import mock "github.com/stretchr/testify/mock"

// MockStmt is an autogenerated mock type for the Stmt type
type MockStmt struct {
	mock.Mock
}

// ColumnNum provides a mock function with given fields:
func (_m *MockStmt) ColumnNum() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *MockStmt) ID() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ParamNum provides a mock function with given fields:
func (_m *MockStmt) ParamNum() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
